server:
  port: 8088
spring:
  application:
    name: gms-configServer
  cloud:
    config:
      server:
        git:
          uri: git@github.com:gehanxiang/gms.git
          search-paths: config-repo
          strict-host-key-checking: false
          private-key:
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAuQv+vxLuqzS4eUgz9s4rRi7C9s2noe6yyarO8dqYIqwWbU72
            QQaHLfq9EbAvDnwnPDc6CXXgtHCPLBhEIFeH71BUBwrImqgw2qYGsaDDs4x8XixQ
            dvPdhrzb7HkX62ypXWrX7XwP2Qwc/Fyoh/bAyr7NFyiMbVYJRYDPR+3ToC7984od
            EPevhQOWfzMgNaMXsO+um91SKC3cnGiEmk0gpr3/ACo2YYEt1Ndnufd5a9DxUp0F
            F5XVOdp+ruqsQmuYrNQ58myzMFQBNGPcaBvtfltMhHknk7RmOEtz2SiLDqm/KGdM
            klm9R5j4WPF3O1Plx9l6XmUXQ9D6S0sU0O5DB/Dz1vWhjCg+VQ4WNNhrkenHv2hW
            EMnr68Isil2PxCUHsUBWBUOdasEqofbtln9G6kjAgaAIQT2/xMI9rxlMuBe3MRxs
            TEVWPSfL/2Wjc2iUryp0CTD8ou2RnY5VtHAjfhlkzox9r2HR/2tifMTgSNDxpMdo
            L9I9PUDUV3uzqH+/bGQJksNf47VtUe33QN1CiuUghRFJ56pvoqM/+zVOKOtSbIEd
            EGJXuWA/K3WO/bOcOiPYp/zQ/38Ln7wlTUA/WVNCekZaLsvsH2+zFWx/ne+UO8No
            D+hKB5P0L9CqsMdETw383R2J0oy7GOx97K405/pBPfHmM1xlZaCEAe3JVEMCAwEA
            AQKCAgBMKZG6VzKAqPxcfslUhdrt0gVQy6h5T+OqeXEfvlbrvmSkrOFSNjuhQxha
            lWdo0NTdReXPSwMngUSMY5h2r1A1wZw0Ic4bSaqB89/BcGfcGLB/mkGsFAdTk5v5
            IoYj0d+LoZQqHOvw67lqbUC4ZWlIiWukYn4Z6lV6k9+8vThjL7Q6btgzyZ4mYymo
            RQS2zt/LZXs6j8dm3il0/tfFIoWT25N/H+CuFRsmBVqeAiupoqAQ3qvf3z2ZyEJo
            ABLSa7K1P8xx6Sd/drPgOlHXT9daMH238J3Hf3KrLPMLqFJDwL37BTlQ6zqqo11k
            Tk5Czu8+aFajT3xZ30OFheuVatuPT1vGx+2BfX2bSSQZPSSzsuiEmYj3byJ762xt
            Q7HsIPut4M63QzelmdF3on4nRjzWH0viEj2EilTsZqkYLAa82HMjNBjGwvlIpkpq
            9RWEFcM5DaodEIAnLLEyjfIICWBhV1nQVzu6sBdNTznpTFkm1ANrXzR+RMAt4HUV
            h1toNJ9OyoNEhOLc+yfSYO65Ry+VYih1b6kVPiA7tAvDedskQXzuSbUMlgPVqJix
            FUJPa2Ktf1Xb1MIIZ1esOyRfZQCsHESVotroIJhzhjnJNnCu+Rbk7CUo9zsC7AuI
            FO7Fsj0Xco28oKroD11xxTsUeflsFA9MPuz06UmiITQPeFwwMQKCAQEA7ST1u0or
            xv0QVwAJrjITpiunzB/g02k65/CAzOLmKS67fn7G/5NHgvtl7KKFEUiQMBJNXWV0
            1DgLexlaSrFSGBvKQCQ9joJ5deAMUD5WpKMRsuRREiWbkDiaQUinMy8rIF93E57p
            9/G4ZpFffeOYkMfVIlA0a3zUTUkanJKqHpB3USJKm/Bjr4W2CgTtGs7kFlFwFh/L
            iMGUqu2ovuwz/e5p4ImQI3xzcRpmYUh5CTotFZB+i+j2+xZxkKz7fYEc8U5i30vv
            RqqWBo6Gjs9Y1Ia1wQdyCjI3B1yDnkMZBAvcHBIzA+OI4+ODpbhx9cE2wpPMgM+7
            wtML838Vi88T7wKCAQEAx8KY/PQIwMbyKJ6Gt/ogNzteVXQm45FpB0E2dGHHbOuq
            1WeiA0k0Xnr+bW8sMIMkK2CAPbRn2d3CPbGtOuLpVl7WAL6gCXO97cJoIGsoAld6
            zIKnOKlwXGBKNDyoJk5J04p6omtiisBuvdWbogkqvphTY0Scp3kvt4QetMq1h4Lc
            JzZ7FEoSAfLx9pNhinLsxnCPKYfeX8XDhd6nrD7b/7v4sapjucGOg6skHmXx2TpQ
            nCKC0V7OjXxP1bT/T+ftVfg/zMo6oMrTsmXgutvk98SY8VTbUzn6vAW0qHqWSpsx
            QRhcLakDnb4oDU6fIrDeSKvw0p72fLcL67ZkPsog7QKCAQEA3jJJRKlkh1hKXRod
            9+fX3VT+LhaYc74fgX8pT9Ax09iDuSxUjNeUo7emcqh8ggs5frFHaAFODCJPL5I7
            tcybnRc81Aig3MyHvdil8PHYAP8B8FpZU+WE8wb2EcFfWGgTwotwaSP3GWiVXRVN
            IgmEw/NZUoNP+n7F9XxPwPDzERxPj+fPfHkrDiT8wjqHZxz/PaIkobY84PBwug9g
            kzOCK6Wd8tMyCO3sxMb1sqVTM0AdSh1PVQx9jhojYmmSYq/9TGQj5BGkKtRfKdmV
            Xm4NT2TBHBI72i3evbkDYeCAqffqzyqGPliNxOlCSp6duKTHCF2vuenqhct1YTts
            Fsl6ZQKCAQBSwfT9vuAtdX53g42OhMp591eSkYdW+jQH9GVp++RR5KSmusNtFxPi
            HJRxpAArrPj8G4OljKsFoJDLXGPHJKDEzo9cSZ0lrVS/Pq5C2AIATluqhGpg2Bmb
            u6yiTYrgK8j8Ib/CsDhoAWcfsHJExAV4ZsUNOCyqWVOCdPL/tYdVN8qbWD/PXQxu
            0Eab/90GLayYXaOB8i8XgGgLev3+JyCfpzFV8aBVIbI4LFvPWC7E7xrcRJPrx5pN
            FXZBtDWd1hkGZ82Ouy1k1gK0Qu7Cmz0VxNYUDTK8HSYaZUa+EeNXz0mtjTkLFZ1Q
            6anQMYVOKvY8JzejGoZFjtQaeDq5pKXVAoIBAAlTTCV1fbWLpGomytkKLEZKQWDK
            z0S2vCg6ggfedM1NDM+02MR9qKbK3GEs8jj37C7BIfwrWfgsVUQqfAPPLmivTAdc
            iNm3rQ/jtUWAO1N95fdqrLwSVMdBPf+7vimn31IA2m1pHeLBaMjUe8NGp8Mn5rnU
            2cMPrGxA4OxL5j6nutoHmQq+oEAlOLkVAJAcPQtoyv1vLNuvpfPdxL4Oa3IDqNSA
            eJUwVA6Y7f95GFoCKQvBN1uP9uLardBQHNwP7fAUzcL9CDQCEDz2XZzf/WrjTQQ4
            DS+QjBesMkTABjbaTf0gSYEu+0T/LDN0j6RHY0ZAd+KRyDxVEMK6POZ5f5Y=
            -----END RSA PRIVATE KEY-----


