server:
  port: 8088
spring:
  application:
    name: gms-configServer
  cloud:
    config:
      server:
        git:
          uri: git@github.com:gehanxiang/gms.git
          search-paths: config-repo
          strict-host-key-checking: false
          private-key:
          default-label: main
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
    prefer-ip-address: true
