server:
  port: 8085
spring:
  application:
    name: gms-feignWithHystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream