server:
  port: 8083
spring:
  application:
    name: gms-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true